# Generated by Django 2.1.2 on 2019-04-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='api_pass',
            field=models.CharField(default='pass', max_length=64),
        ),
    ]
