# Generated by Django 2.1.2 on 2019-04-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_operator_api_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='api_pass',
            field=models.CharField(default='pass', max_length=256),
        ),
    ]
